# Generated by Django 2.2.4 on 2021-02-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semirestful_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='date',
            field=models.DateField(default='1900-12-01'),
        ),
    ]
