# Generated by Django 2.2.4 on 2021-02-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='person'),
            preserve_default=False,
        ),
    ]
