# Generated by Django 2.2.4 on 2021-02-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='birth',
            field=models.DateField(default='1995-12-06'),
            preserve_default=False,
        ),
    ]
